package com.v2ray.ang.nimbus

import android.content.Context
import com.v2ray.ang.dto.entities.ProfileItem
import com.v2ray.ang.handler.MmkvManager

/**
 * Single Nimbus pipeline boundary:
 * import -> classify -> harden transport -> persist -> scanner.
 *
 * The Xray config remains generated by the upstream PattNG/V2rayNG builder;
 * this layer only prepares the ProfileItem consumed by that builder.
 */
object NimbusConfigPipeline {
    fun prepareProfile(profile: ProfileItem): ProfileItem? {
        if (!NimbusPolicy.isSupported(profile)) return null
        return NimbusPolicy.prepare(profile)
    }

    fun prepareAndPersist(guid: String): Boolean {
        val profile = MmkvManager.decodeServerConfig(guid) ?: return false
        val prepared = prepareProfile(profile) ?: return false
        MmkvManager.encodeServerConfig(guid, prepared)
        return true
    }

    fun filterSubscription(context: Context, subId: String): Int =
        NimbusPolicy.filterSubscription(subId)

    fun filterAllSubscriptions(context: Context): Int =
        NimbusPolicy.filterAllSubscriptions()

    fun onProfileSaved(context: Context, guid: String) {
        if (!prepareAndPersist(guid)) return
        NimbusScheduler.enqueueImmediate(context, guid)
        NimbusScheduler.schedule(context)
    }
}
